version: "3"

services:
  gocqhttp:
    container_name: pcr_cq
    build: ./setting/goCqhttp
    ports:
      - "8088:8088"
    privileged: true
    restart: always
    stdin_open: true
    tty: true
    networks:
      web:
        ipv4_address: 172.200.1.3
    volumes:
      - ./setting/goCqhttp/file/:/opt/
  php:
    container_name: pcr_php
    build: ./setting/php
    privileged: true
    restart: always
    working_dir: /www
    expose:
      - "9000"
    networks:
      web:
        ipv4_address: 172.200.1.2
    volumes:
      - ./setting/php/php.ini:/usr/local/etc/php/php.ini
      - ./project:/www
      - ./setting/php/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./setting/php/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./setting/php/supervisord/conf/:/etc/supervisor/conf.d/
      - ./setting/php/supervisord/log/:/tmp/supervisord/
networks:
  web:
    external: true
    name: pcr
