version: "3"

services:
  gocqhttp:
    container_name: pcr_cq
    build: ./setting/goCqhttp
    ports:
      - "8088:8088"
    privileged: true
    restart: always
    stdin_open: true
    tty: true
    volumes: 
      - ./setting/goCqhttp/file/:/opt/