version: "3"

services:
  gocqhttp:
    container_name: pcr_cq
    build: ./setting/goCqhttp
    ports:
      - "8088:8088"
    privileged: true
    restart: always
    stdin_open: true
    tty: true
    networks:
      pcr:
        ipv4_address: 172.200.1.3
    volumes:
      - ./setting/goCqhttp/cqhttp/:/go/cqhttp/
      - ./setting/goCqhttp/app/:/go/app/
  minio:
    image: minio/minio:latest
    container_name: pcr_minio
    networks:
      pcr:
        ipv4_address: 172.200.1.4
    ports:
      - "9000:9000"
    restart: always
    command: server /data
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123 #大于等于8位
    logging:
      options:
        max-size: "30M" # 最大文件上传限制
      driver: json-file
    volumes:
      # 必须先创建目录
      - ./setting/minio/data:/data # 映射文件路径
      - ./setting/minio/config:/root/.minio# 映射文件路径
  php:
    container_name: pcr_php
    build: ./setting/php
    privileged: true
    restart: always
    working_dir: /www
    expose:
      - "9000"
    networks:
      pcr:
        ipv4_address: 172.200.1.2
    volumes:
      - ./setting/php/php.ini:/usr/local/etc/php/php.ini
      - ./project:/www
      - ./setting/minio/data:/images
      - ./setting/php/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./setting/php/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./setting/php/supervisord/conf/:/etc/supervisor/conf.d/
      - ./setting/php/supervisord/log/:/tmp/supervisord/
networks:
  pcr:
    external: true
